// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"

	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: DefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					NatsAccountBytesReceived: MetricConfig{
						Enabled: true,
					},
					NatsAccountBytesSent: MetricConfig{
						Enabled: true,
					},
					NatsAccountConnections: MetricConfig{
						Enabled: true,
					},
					NatsAccountLeafNodes: MetricConfig{
						Enabled: true,
					},
					NatsAccountMessagesReceived: MetricConfig{
						Enabled: true,
					},
					NatsAccountMessagesSent: MetricConfig{
						Enabled: true,
					},
					NatsAccountSlowConsumers: MetricConfig{
						Enabled: true,
					},
					NatsAccountSubscriptions: MetricConfig{
						Enabled: true,
					},
					NatsConnectionCount: MetricConfig{
						Enabled: true,
					},
					NatsJetstreamAPICalls: MetricConfig{
						Enabled: true,
					},
					NatsJetstreamAPIErrors: MetricConfig{
						Enabled: true,
					},
					NatsJetstreamBytes: MetricConfig{
						Enabled: true,
					},
					NatsJetstreamConsumers: MetricConfig{
						Enabled: true,
					},
					NatsJetstreamMemoryReserved: MetricConfig{
						Enabled: true,
					},
					NatsJetstreamMessages: MetricConfig{
						Enabled: true,
					},
					NatsJetstreamStorageReserved: MetricConfig{
						Enabled: true,
					},
					NatsJetstreamStreams: MetricConfig{
						Enabled: true,
					},
					NatsServerBytesReceived: MetricConfig{
						Enabled: true,
					},
					NatsServerBytesSent: MetricConfig{
						Enabled: true,
					},
					NatsServerConnections: MetricConfig{
						Enabled: true,
					},
					NatsServerConnectionsTotal: MetricConfig{
						Enabled: true,
					},
					NatsServerCPU: MetricConfig{
						Enabled: true,
					},
					NatsServerLeafNodes: MetricConfig{
						Enabled: true,
					},
					NatsServerMaxConnections: MetricConfig{
						Enabled: true,
					},
					NatsServerMemory: MetricConfig{
						Enabled: true,
					},
					NatsServerMessagesReceived: MetricConfig{
						Enabled: true,
					},
					NatsServerMessagesSent: MetricConfig{
						Enabled: true,
					},
					NatsServerRoutes: MetricConfig{
						Enabled: true,
					},
					NatsServerSlowConsumers: MetricConfig{
						Enabled: true,
					},
					NatsServerSubscriptions: MetricConfig{
						Enabled: true,
					},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					NatsAccountBytesReceived: MetricConfig{
						Enabled: false,
					},
					NatsAccountBytesSent: MetricConfig{
						Enabled: false,
					},
					NatsAccountConnections: MetricConfig{
						Enabled: false,
					},
					NatsAccountLeafNodes: MetricConfig{
						Enabled: false,
					},
					NatsAccountMessagesReceived: MetricConfig{
						Enabled: false,
					},
					NatsAccountMessagesSent: MetricConfig{
						Enabled: false,
					},
					NatsAccountSlowConsumers: MetricConfig{
						Enabled: false,
					},
					NatsAccountSubscriptions: MetricConfig{
						Enabled: false,
					},
					NatsConnectionCount: MetricConfig{
						Enabled: false,
					},
					NatsJetstreamAPICalls: MetricConfig{
						Enabled: false,
					},
					NatsJetstreamAPIErrors: MetricConfig{
						Enabled: false,
					},
					NatsJetstreamBytes: MetricConfig{
						Enabled: false,
					},
					NatsJetstreamConsumers: MetricConfig{
						Enabled: false,
					},
					NatsJetstreamMemoryReserved: MetricConfig{
						Enabled: false,
					},
					NatsJetstreamMessages: MetricConfig{
						Enabled: false,
					},
					NatsJetstreamStorageReserved: MetricConfig{
						Enabled: false,
					},
					NatsJetstreamStreams: MetricConfig{
						Enabled: false,
					},
					NatsServerBytesReceived: MetricConfig{
						Enabled: false,
					},
					NatsServerBytesSent: MetricConfig{
						Enabled: false,
					},
					NatsServerConnections: MetricConfig{
						Enabled: false,
					},
					NatsServerConnectionsTotal: MetricConfig{
						Enabled: false,
					},
					NatsServerCPU: MetricConfig{
						Enabled: false,
					},
					NatsServerLeafNodes: MetricConfig{
						Enabled: false,
					},
					NatsServerMaxConnections: MetricConfig{
						Enabled: false,
					},
					NatsServerMemory: MetricConfig{
						Enabled: false,
					},
					NatsServerMessagesReceived: MetricConfig{
						Enabled: false,
					},
					NatsServerMessagesSent: MetricConfig{
						Enabled: false,
					},
					NatsServerRoutes: MetricConfig{
						Enabled: false,
					},
					NatsServerSlowConsumers: MetricConfig{
						Enabled: false,
					},
					NatsServerSubscriptions: MetricConfig{
						Enabled: false,
					},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(MetricConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := DefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}
