// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for natsmetrics metrics.
type MetricsConfig struct {
	NatsAccountBytesReceived     MetricConfig `mapstructure:"nats.account.bytes.received"`
	NatsAccountBytesSent         MetricConfig `mapstructure:"nats.account.bytes.sent"`
	NatsAccountConnections       MetricConfig `mapstructure:"nats.account.connections"`
	NatsAccountLeafNodes         MetricConfig `mapstructure:"nats.account.leaf_nodes"`
	NatsAccountMessagesReceived  MetricConfig `mapstructure:"nats.account.messages.received"`
	NatsAccountMessagesSent      MetricConfig `mapstructure:"nats.account.messages.sent"`
	NatsAccountSlowConsumers     MetricConfig `mapstructure:"nats.account.slow_consumers"`
	NatsAccountSubscriptions     MetricConfig `mapstructure:"nats.account.subscriptions"`
	NatsConnectionCount          MetricConfig `mapstructure:"nats.connection.count"`
	NatsJetstreamAPICalls        MetricConfig `mapstructure:"nats.jetstream.api.calls"`
	NatsJetstreamAPIErrors       MetricConfig `mapstructure:"nats.jetstream.api.errors"`
	NatsJetstreamBytes           MetricConfig `mapstructure:"nats.jetstream.bytes"`
	NatsJetstreamConsumers       MetricConfig `mapstructure:"nats.jetstream.consumers"`
	NatsJetstreamMemoryReserved  MetricConfig `mapstructure:"nats.jetstream.memory.reserved"`
	NatsJetstreamMessages        MetricConfig `mapstructure:"nats.jetstream.messages"`
	NatsJetstreamStorageReserved MetricConfig `mapstructure:"nats.jetstream.storage.reserved"`
	NatsJetstreamStreams         MetricConfig `mapstructure:"nats.jetstream.streams"`
	NatsServerBytesReceived      MetricConfig `mapstructure:"nats.server.bytes.received"`
	NatsServerBytesSent          MetricConfig `mapstructure:"nats.server.bytes.sent"`
	NatsServerConnections        MetricConfig `mapstructure:"nats.server.connections"`
	NatsServerConnectionsTotal   MetricConfig `mapstructure:"nats.server.connections.total"`
	NatsServerCPU                MetricConfig `mapstructure:"nats.server.cpu"`
	NatsServerLeafNodes          MetricConfig `mapstructure:"nats.server.leaf_nodes"`
	NatsServerMaxConnections     MetricConfig `mapstructure:"nats.server.max_connections"`
	NatsServerMemory             MetricConfig `mapstructure:"nats.server.memory"`
	NatsServerMessagesReceived   MetricConfig `mapstructure:"nats.server.messages.received"`
	NatsServerMessagesSent       MetricConfig `mapstructure:"nats.server.messages.sent"`
	NatsServerRoutes             MetricConfig `mapstructure:"nats.server.routes"`
	NatsServerSlowConsumers      MetricConfig `mapstructure:"nats.server.slow_consumers"`
	NatsServerSubscriptions      MetricConfig `mapstructure:"nats.server.subscriptions"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		NatsAccountBytesReceived: MetricConfig{
			Enabled: true,
		},
		NatsAccountBytesSent: MetricConfig{
			Enabled: true,
		},
		NatsAccountConnections: MetricConfig{
			Enabled: true,
		},
		NatsAccountLeafNodes: MetricConfig{
			Enabled: true,
		},
		NatsAccountMessagesReceived: MetricConfig{
			Enabled: true,
		},
		NatsAccountMessagesSent: MetricConfig{
			Enabled: true,
		},
		NatsAccountSlowConsumers: MetricConfig{
			Enabled: true,
		},
		NatsAccountSubscriptions: MetricConfig{
			Enabled: true,
		},
		NatsConnectionCount: MetricConfig{
			Enabled: true,
		},
		NatsJetstreamAPICalls: MetricConfig{
			Enabled: true,
		},
		NatsJetstreamAPIErrors: MetricConfig{
			Enabled: true,
		},
		NatsJetstreamBytes: MetricConfig{
			Enabled: true,
		},
		NatsJetstreamConsumers: MetricConfig{
			Enabled: true,
		},
		NatsJetstreamMemoryReserved: MetricConfig{
			Enabled: true,
		},
		NatsJetstreamMessages: MetricConfig{
			Enabled: true,
		},
		NatsJetstreamStorageReserved: MetricConfig{
			Enabled: true,
		},
		NatsJetstreamStreams: MetricConfig{
			Enabled: true,
		},
		NatsServerBytesReceived: MetricConfig{
			Enabled: true,
		},
		NatsServerBytesSent: MetricConfig{
			Enabled: true,
		},
		NatsServerConnections: MetricConfig{
			Enabled: true,
		},
		NatsServerConnectionsTotal: MetricConfig{
			Enabled: true,
		},
		NatsServerCPU: MetricConfig{
			Enabled: true,
		},
		NatsServerLeafNodes: MetricConfig{
			Enabled: true,
		},
		NatsServerMaxConnections: MetricConfig{
			Enabled: true,
		},
		NatsServerMemory: MetricConfig{
			Enabled: true,
		},
		NatsServerMessagesReceived: MetricConfig{
			Enabled: true,
		},
		NatsServerMessagesSent: MetricConfig{
			Enabled: true,
		},
		NatsServerRoutes: MetricConfig{
			Enabled: true,
		},
		NatsServerSlowConsumers: MetricConfig{
			Enabled: true,
		},
		NatsServerSubscriptions: MetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for natsmetrics metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}
