// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))

			expectedWarnings := 0
			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsAccountBytesReceivedDataPoint(ts, 1, "account-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsAccountBytesSentDataPoint(ts, 1, "account-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsAccountConnectionsDataPoint(ts, 1, "account-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsAccountLeafNodesDataPoint(ts, 1, "account-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsAccountMessagesReceivedDataPoint(ts, 1, "account-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsAccountMessagesSentDataPoint(ts, 1, "account-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsAccountSlowConsumersDataPoint(ts, 1, "account-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsAccountSubscriptionsDataPoint(ts, 1, "account-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsConnectionCountDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsJetstreamAPICallsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsJetstreamAPIErrorsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsJetstreamBytesDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsJetstreamConsumersDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsJetstreamMemoryReservedDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsJetstreamMessagesDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsJetstreamStorageReservedDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsJetstreamStreamsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsServerBytesReceivedDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsServerBytesSentDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsServerConnectionsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsServerConnectionsTotalDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsServerCPUDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsServerLeafNodesDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsServerMaxConnectionsDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsServerMemoryDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsServerMessagesReceivedDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsServerMessagesSentDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsServerRoutesDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsServerSlowConsumersDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNatsServerSubscriptionsDataPoint(ts, 1)

			res := pcommon.NewResource()
			metrics := mb.Emit(WithResource(res))

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			var allMetricsList []pmetric.Metric
			totalMetricsCount := 0
			for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
				rm := metrics.ResourceMetrics().At(ri)
				assert.Equal(t, 1, rm.ScopeMetrics().Len())
				ms := rm.ScopeMetrics().At(0).Metrics()
				totalMetricsCount += ms.Len()
				for mi := 0; mi < ms.Len(); mi++ {
					allMetricsList = append(allMetricsList, ms.At(mi))
				}
			}
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, totalMetricsCount)
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, totalMetricsCount)
			}
			validatedMetrics := make(map[string]bool)
			for _, mi := range allMetricsList {
				switch mi.Name() {
				case "nats.account.bytes.received":
					assert.False(t, validatedMetrics["nats.account.bytes.received"], "Found a duplicate in the metrics slice: nats.account.bytes.received")
					validatedMetrics["nats.account.bytes.received"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total bytes received for the account since server start.", mi.Description())
					assert.Equal(t, "By", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					accountAttrVal, ok := dp.Attributes().Get("account")
					assert.True(t, ok)
					assert.Equal(t, "account-val", accountAttrVal.Str())
				case "nats.account.bytes.sent":
					assert.False(t, validatedMetrics["nats.account.bytes.sent"], "Found a duplicate in the metrics slice: nats.account.bytes.sent")
					validatedMetrics["nats.account.bytes.sent"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total bytes sent for the account since server start.", mi.Description())
					assert.Equal(t, "By", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					accountAttrVal, ok := dp.Attributes().Get("account")
					assert.True(t, ok)
					assert.Equal(t, "account-val", accountAttrVal.Str())
				case "nats.account.connections":
					assert.False(t, validatedMetrics["nats.account.connections"], "Found a duplicate in the metrics slice: nats.account.connections")
					validatedMetrics["nats.account.connections"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Number of active client connections for the account.", mi.Description())
					assert.Equal(t, "{connections}", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					accountAttrVal, ok := dp.Attributes().Get("account")
					assert.True(t, ok)
					assert.Equal(t, "account-val", accountAttrVal.Str())
				case "nats.account.leaf_nodes":
					assert.False(t, validatedMetrics["nats.account.leaf_nodes"], "Found a duplicate in the metrics slice: nats.account.leaf_nodes")
					validatedMetrics["nats.account.leaf_nodes"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Number of active leaf node connections for the account.", mi.Description())
					assert.Equal(t, "{leaf_nodes}", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					accountAttrVal, ok := dp.Attributes().Get("account")
					assert.True(t, ok)
					assert.Equal(t, "account-val", accountAttrVal.Str())
				case "nats.account.messages.received":
					assert.False(t, validatedMetrics["nats.account.messages.received"], "Found a duplicate in the metrics slice: nats.account.messages.received")
					validatedMetrics["nats.account.messages.received"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total messages received for the account since server start.", mi.Description())
					assert.Equal(t, "{messages}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					accountAttrVal, ok := dp.Attributes().Get("account")
					assert.True(t, ok)
					assert.Equal(t, "account-val", accountAttrVal.Str())
				case "nats.account.messages.sent":
					assert.False(t, validatedMetrics["nats.account.messages.sent"], "Found a duplicate in the metrics slice: nats.account.messages.sent")
					validatedMetrics["nats.account.messages.sent"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total messages sent for the account since server start.", mi.Description())
					assert.Equal(t, "{messages}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					accountAttrVal, ok := dp.Attributes().Get("account")
					assert.True(t, ok)
					assert.Equal(t, "account-val", accountAttrVal.Str())
				case "nats.account.slow_consumers":
					assert.False(t, validatedMetrics["nats.account.slow_consumers"], "Found a duplicate in the metrics slice: nats.account.slow_consumers")
					validatedMetrics["nats.account.slow_consumers"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Number of slow consumer events for the account.", mi.Description())
					assert.Equal(t, "{consumers}", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					accountAttrVal, ok := dp.Attributes().Get("account")
					assert.True(t, ok)
					assert.Equal(t, "account-val", accountAttrVal.Str())
				case "nats.account.subscriptions":
					assert.False(t, validatedMetrics["nats.account.subscriptions"], "Found a duplicate in the metrics slice: nats.account.subscriptions")
					validatedMetrics["nats.account.subscriptions"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Number of active subscriptions for the account.", mi.Description())
					assert.Equal(t, "{subscriptions}", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					accountAttrVal, ok := dp.Attributes().Get("account")
					assert.True(t, ok)
					assert.Equal(t, "account-val", accountAttrVal.Str())
				case "nats.connection.count":
					assert.False(t, validatedMetrics["nats.connection.count"], "Found a duplicate in the metrics slice: nats.connection.count")
					validatedMetrics["nats.connection.count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Number of active client connections.", mi.Description())
					assert.Equal(t, "{connections}", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nats.jetstream.api.calls":
					assert.False(t, validatedMetrics["nats.jetstream.api.calls"], "Found a duplicate in the metrics slice: nats.jetstream.api.calls")
					validatedMetrics["nats.jetstream.api.calls"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total JetStream API calls since server start.", mi.Description())
					assert.Equal(t, "{calls}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nats.jetstream.api.errors":
					assert.False(t, validatedMetrics["nats.jetstream.api.errors"], "Found a duplicate in the metrics slice: nats.jetstream.api.errors")
					validatedMetrics["nats.jetstream.api.errors"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total JetStream API errors since server start.", mi.Description())
					assert.Equal(t, "{errors}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nats.jetstream.bytes":
					assert.False(t, validatedMetrics["nats.jetstream.bytes"], "Found a duplicate in the metrics slice: nats.jetstream.bytes")
					validatedMetrics["nats.jetstream.bytes"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Total bytes stored in JetStream.", mi.Description())
					assert.Equal(t, "By", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nats.jetstream.consumers":
					assert.False(t, validatedMetrics["nats.jetstream.consumers"], "Found a duplicate in the metrics slice: nats.jetstream.consumers")
					validatedMetrics["nats.jetstream.consumers"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Number of JetStream consumers.", mi.Description())
					assert.Equal(t, "{consumers}", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nats.jetstream.memory.reserved":
					assert.False(t, validatedMetrics["nats.jetstream.memory.reserved"], "Found a duplicate in the metrics slice: nats.jetstream.memory.reserved")
					validatedMetrics["nats.jetstream.memory.reserved"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Memory reserved by JetStream.", mi.Description())
					assert.Equal(t, "By", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nats.jetstream.messages":
					assert.False(t, validatedMetrics["nats.jetstream.messages"], "Found a duplicate in the metrics slice: nats.jetstream.messages")
					validatedMetrics["nats.jetstream.messages"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Total number of messages stored in JetStream.", mi.Description())
					assert.Equal(t, "{messages}", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nats.jetstream.storage.reserved":
					assert.False(t, validatedMetrics["nats.jetstream.storage.reserved"], "Found a duplicate in the metrics slice: nats.jetstream.storage.reserved")
					validatedMetrics["nats.jetstream.storage.reserved"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Disk storage reserved by JetStream.", mi.Description())
					assert.Equal(t, "By", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nats.jetstream.streams":
					assert.False(t, validatedMetrics["nats.jetstream.streams"], "Found a duplicate in the metrics slice: nats.jetstream.streams")
					validatedMetrics["nats.jetstream.streams"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Number of JetStream streams.", mi.Description())
					assert.Equal(t, "{streams}", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nats.server.bytes.received":
					assert.False(t, validatedMetrics["nats.server.bytes.received"], "Found a duplicate in the metrics slice: nats.server.bytes.received")
					validatedMetrics["nats.server.bytes.received"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total number of bytes received by the NATS server since it started.", mi.Description())
					assert.Equal(t, "By", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nats.server.bytes.sent":
					assert.False(t, validatedMetrics["nats.server.bytes.sent"], "Found a duplicate in the metrics slice: nats.server.bytes.sent")
					validatedMetrics["nats.server.bytes.sent"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total number of bytes sent by the NATS server since it started.", mi.Description())
					assert.Equal(t, "By", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nats.server.connections":
					assert.False(t, validatedMetrics["nats.server.connections"], "Found a duplicate in the metrics slice: nats.server.connections")
					validatedMetrics["nats.server.connections"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Number of active client connections to the NATS server.", mi.Description())
					assert.Equal(t, "{connections}", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nats.server.connections.total":
					assert.False(t, validatedMetrics["nats.server.connections.total"], "Found a duplicate in the metrics slice: nats.server.connections.total")
					validatedMetrics["nats.server.connections.total"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total number of client connections to the NATS server since it started.", mi.Description())
					assert.Equal(t, "{connections}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nats.server.cpu":
					assert.False(t, validatedMetrics["nats.server.cpu"], "Found a duplicate in the metrics slice: nats.server.cpu")
					validatedMetrics["nats.server.cpu"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "CPU usage of the NATS server process (0-100).", mi.Description())
					assert.Equal(t, "%", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				case "nats.server.leaf_nodes":
					assert.False(t, validatedMetrics["nats.server.leaf_nodes"], "Found a duplicate in the metrics slice: nats.server.leaf_nodes")
					validatedMetrics["nats.server.leaf_nodes"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Number of active leaf node connections to the NATS server.", mi.Description())
					assert.Equal(t, "{leaf_nodes}", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nats.server.max_connections":
					assert.False(t, validatedMetrics["nats.server.max_connections"], "Found a duplicate in the metrics slice: nats.server.max_connections")
					validatedMetrics["nats.server.max_connections"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Maximum number of client connections allowed by the NATS server.", mi.Description())
					assert.Equal(t, "{connections}", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nats.server.memory":
					assert.False(t, validatedMetrics["nats.server.memory"], "Found a duplicate in the metrics slice: nats.server.memory")
					validatedMetrics["nats.server.memory"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Memory used by the NATS server process.", mi.Description())
					assert.Equal(t, "By", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nats.server.messages.received":
					assert.False(t, validatedMetrics["nats.server.messages.received"], "Found a duplicate in the metrics slice: nats.server.messages.received")
					validatedMetrics["nats.server.messages.received"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total number of messages received by the NATS server since it started.", mi.Description())
					assert.Equal(t, "{messages}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nats.server.messages.sent":
					assert.False(t, validatedMetrics["nats.server.messages.sent"], "Found a duplicate in the metrics slice: nats.server.messages.sent")
					validatedMetrics["nats.server.messages.sent"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Total number of messages sent by the NATS server since it started.", mi.Description())
					assert.Equal(t, "{messages}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nats.server.routes":
					assert.False(t, validatedMetrics["nats.server.routes"], "Found a duplicate in the metrics slice: nats.server.routes")
					validatedMetrics["nats.server.routes"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Number of active cluster routes on the NATS server.", mi.Description())
					assert.Equal(t, "{routes}", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nats.server.slow_consumers":
					assert.False(t, validatedMetrics["nats.server.slow_consumers"], "Found a duplicate in the metrics slice: nats.server.slow_consumers")
					validatedMetrics["nats.server.slow_consumers"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Number of slow consumer events on the NATS server.", mi.Description())
					assert.Equal(t, "{consumers}", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "nats.server.subscriptions":
					assert.False(t, validatedMetrics["nats.server.subscriptions"], "Found a duplicate in the metrics slice: nats.server.subscriptions")
					validatedMetrics["nats.server.subscriptions"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Number of active subscriptions on the NATS server.", mi.Description())
					assert.Equal(t, "{subscriptions}", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				}
			}
		})
	}
}
