// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"time"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
)

var MetricsInfo = metricsInfo{
	NatsAccountBytesReceived: metricInfo{
		Name: "nats.account.bytes.received",
	},
	NatsAccountBytesSent: metricInfo{
		Name: "nats.account.bytes.sent",
	},
	NatsAccountConnections: metricInfo{
		Name: "nats.account.connections",
	},
	NatsAccountLeafNodes: metricInfo{
		Name: "nats.account.leaf_nodes",
	},
	NatsAccountMessagesReceived: metricInfo{
		Name: "nats.account.messages.received",
	},
	NatsAccountMessagesSent: metricInfo{
		Name: "nats.account.messages.sent",
	},
	NatsAccountSlowConsumers: metricInfo{
		Name: "nats.account.slow_consumers",
	},
	NatsAccountSubscriptions: metricInfo{
		Name: "nats.account.subscriptions",
	},
	NatsConnectionCount: metricInfo{
		Name: "nats.connection.count",
	},
	NatsJetstreamAPICalls: metricInfo{
		Name: "nats.jetstream.api.calls",
	},
	NatsJetstreamAPIErrors: metricInfo{
		Name: "nats.jetstream.api.errors",
	},
	NatsJetstreamBytes: metricInfo{
		Name: "nats.jetstream.bytes",
	},
	NatsJetstreamConsumers: metricInfo{
		Name: "nats.jetstream.consumers",
	},
	NatsJetstreamMemoryReserved: metricInfo{
		Name: "nats.jetstream.memory.reserved",
	},
	NatsJetstreamMessages: metricInfo{
		Name: "nats.jetstream.messages",
	},
	NatsJetstreamStorageReserved: metricInfo{
		Name: "nats.jetstream.storage.reserved",
	},
	NatsJetstreamStreams: metricInfo{
		Name: "nats.jetstream.streams",
	},
	NatsServerBytesReceived: metricInfo{
		Name: "nats.server.bytes.received",
	},
	NatsServerBytesSent: metricInfo{
		Name: "nats.server.bytes.sent",
	},
	NatsServerConnections: metricInfo{
		Name: "nats.server.connections",
	},
	NatsServerConnectionsTotal: metricInfo{
		Name: "nats.server.connections.total",
	},
	NatsServerCPU: metricInfo{
		Name: "nats.server.cpu",
	},
	NatsServerLeafNodes: metricInfo{
		Name: "nats.server.leaf_nodes",
	},
	NatsServerMaxConnections: metricInfo{
		Name: "nats.server.max_connections",
	},
	NatsServerMemory: metricInfo{
		Name: "nats.server.memory",
	},
	NatsServerMessagesReceived: metricInfo{
		Name: "nats.server.messages.received",
	},
	NatsServerMessagesSent: metricInfo{
		Name: "nats.server.messages.sent",
	},
	NatsServerRoutes: metricInfo{
		Name: "nats.server.routes",
	},
	NatsServerSlowConsumers: metricInfo{
		Name: "nats.server.slow_consumers",
	},
	NatsServerSubscriptions: metricInfo{
		Name: "nats.server.subscriptions",
	},
}

type metricsInfo struct {
	NatsAccountBytesReceived     metricInfo
	NatsAccountBytesSent         metricInfo
	NatsAccountConnections       metricInfo
	NatsAccountLeafNodes         metricInfo
	NatsAccountMessagesReceived  metricInfo
	NatsAccountMessagesSent      metricInfo
	NatsAccountSlowConsumers     metricInfo
	NatsAccountSubscriptions     metricInfo
	NatsConnectionCount          metricInfo
	NatsJetstreamAPICalls        metricInfo
	NatsJetstreamAPIErrors       metricInfo
	NatsJetstreamBytes           metricInfo
	NatsJetstreamConsumers       metricInfo
	NatsJetstreamMemoryReserved  metricInfo
	NatsJetstreamMessages        metricInfo
	NatsJetstreamStorageReserved metricInfo
	NatsJetstreamStreams         metricInfo
	NatsServerBytesReceived      metricInfo
	NatsServerBytesSent          metricInfo
	NatsServerConnections        metricInfo
	NatsServerConnectionsTotal   metricInfo
	NatsServerCPU                metricInfo
	NatsServerLeafNodes          metricInfo
	NatsServerMaxConnections     metricInfo
	NatsServerMemory             metricInfo
	NatsServerMessagesReceived   metricInfo
	NatsServerMessagesSent       metricInfo
	NatsServerRoutes             metricInfo
	NatsServerSlowConsumers      metricInfo
	NatsServerSubscriptions      metricInfo
}

type metricInfo struct {
	Name string
}

type metricNatsAccountBytesReceived struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.account.bytes.received metric with initial data.
func (m *metricNatsAccountBytesReceived) init() {
	m.data.SetName("nats.account.bytes.received")
	m.data.SetDescription("Total bytes received for the account since server start.")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNatsAccountBytesReceived) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, accountAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("account", accountAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsAccountBytesReceived) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsAccountBytesReceived) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsAccountBytesReceived(cfg MetricConfig) metricNatsAccountBytesReceived {
	m := metricNatsAccountBytesReceived{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsAccountBytesSent struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.account.bytes.sent metric with initial data.
func (m *metricNatsAccountBytesSent) init() {
	m.data.SetName("nats.account.bytes.sent")
	m.data.SetDescription("Total bytes sent for the account since server start.")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNatsAccountBytesSent) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, accountAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("account", accountAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsAccountBytesSent) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsAccountBytesSent) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsAccountBytesSent(cfg MetricConfig) metricNatsAccountBytesSent {
	m := metricNatsAccountBytesSent{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsAccountConnections struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.account.connections metric with initial data.
func (m *metricNatsAccountConnections) init() {
	m.data.SetName("nats.account.connections")
	m.data.SetDescription("Number of active client connections for the account.")
	m.data.SetUnit("{connections}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNatsAccountConnections) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, accountAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("account", accountAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsAccountConnections) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsAccountConnections) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsAccountConnections(cfg MetricConfig) metricNatsAccountConnections {
	m := metricNatsAccountConnections{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsAccountLeafNodes struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.account.leaf_nodes metric with initial data.
func (m *metricNatsAccountLeafNodes) init() {
	m.data.SetName("nats.account.leaf_nodes")
	m.data.SetDescription("Number of active leaf node connections for the account.")
	m.data.SetUnit("{leaf_nodes}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNatsAccountLeafNodes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, accountAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("account", accountAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsAccountLeafNodes) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsAccountLeafNodes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsAccountLeafNodes(cfg MetricConfig) metricNatsAccountLeafNodes {
	m := metricNatsAccountLeafNodes{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsAccountMessagesReceived struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.account.messages.received metric with initial data.
func (m *metricNatsAccountMessagesReceived) init() {
	m.data.SetName("nats.account.messages.received")
	m.data.SetDescription("Total messages received for the account since server start.")
	m.data.SetUnit("{messages}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNatsAccountMessagesReceived) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, accountAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("account", accountAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsAccountMessagesReceived) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsAccountMessagesReceived) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsAccountMessagesReceived(cfg MetricConfig) metricNatsAccountMessagesReceived {
	m := metricNatsAccountMessagesReceived{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsAccountMessagesSent struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.account.messages.sent metric with initial data.
func (m *metricNatsAccountMessagesSent) init() {
	m.data.SetName("nats.account.messages.sent")
	m.data.SetDescription("Total messages sent for the account since server start.")
	m.data.SetUnit("{messages}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNatsAccountMessagesSent) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, accountAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("account", accountAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsAccountMessagesSent) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsAccountMessagesSent) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsAccountMessagesSent(cfg MetricConfig) metricNatsAccountMessagesSent {
	m := metricNatsAccountMessagesSent{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsAccountSlowConsumers struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.account.slow_consumers metric with initial data.
func (m *metricNatsAccountSlowConsumers) init() {
	m.data.SetName("nats.account.slow_consumers")
	m.data.SetDescription("Number of slow consumer events for the account.")
	m.data.SetUnit("{consumers}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNatsAccountSlowConsumers) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, accountAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("account", accountAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsAccountSlowConsumers) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsAccountSlowConsumers) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsAccountSlowConsumers(cfg MetricConfig) metricNatsAccountSlowConsumers {
	m := metricNatsAccountSlowConsumers{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsAccountSubscriptions struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.account.subscriptions metric with initial data.
func (m *metricNatsAccountSubscriptions) init() {
	m.data.SetName("nats.account.subscriptions")
	m.data.SetDescription("Number of active subscriptions for the account.")
	m.data.SetUnit("{subscriptions}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricNatsAccountSubscriptions) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, accountAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("account", accountAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsAccountSubscriptions) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsAccountSubscriptions) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsAccountSubscriptions(cfg MetricConfig) metricNatsAccountSubscriptions {
	m := metricNatsAccountSubscriptions{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsConnectionCount struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.connection.count metric with initial data.
func (m *metricNatsConnectionCount) init() {
	m.data.SetName("nats.connection.count")
	m.data.SetDescription("Number of active client connections.")
	m.data.SetUnit("{connections}")
	m.data.SetEmptyGauge()
}

func (m *metricNatsConnectionCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsConnectionCount) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsConnectionCount) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsConnectionCount(cfg MetricConfig) metricNatsConnectionCount {
	m := metricNatsConnectionCount{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsJetstreamAPICalls struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.jetstream.api.calls metric with initial data.
func (m *metricNatsJetstreamAPICalls) init() {
	m.data.SetName("nats.jetstream.api.calls")
	m.data.SetDescription("Total JetStream API calls since server start.")
	m.data.SetUnit("{calls}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNatsJetstreamAPICalls) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsJetstreamAPICalls) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsJetstreamAPICalls) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsJetstreamAPICalls(cfg MetricConfig) metricNatsJetstreamAPICalls {
	m := metricNatsJetstreamAPICalls{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsJetstreamAPIErrors struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.jetstream.api.errors metric with initial data.
func (m *metricNatsJetstreamAPIErrors) init() {
	m.data.SetName("nats.jetstream.api.errors")
	m.data.SetDescription("Total JetStream API errors since server start.")
	m.data.SetUnit("{errors}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNatsJetstreamAPIErrors) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsJetstreamAPIErrors) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsJetstreamAPIErrors) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsJetstreamAPIErrors(cfg MetricConfig) metricNatsJetstreamAPIErrors {
	m := metricNatsJetstreamAPIErrors{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsJetstreamBytes struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.jetstream.bytes metric with initial data.
func (m *metricNatsJetstreamBytes) init() {
	m.data.SetName("nats.jetstream.bytes")
	m.data.SetDescription("Total bytes stored in JetStream.")
	m.data.SetUnit("By")
	m.data.SetEmptyGauge()
}

func (m *metricNatsJetstreamBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsJetstreamBytes) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsJetstreamBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsJetstreamBytes(cfg MetricConfig) metricNatsJetstreamBytes {
	m := metricNatsJetstreamBytes{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsJetstreamConsumers struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.jetstream.consumers metric with initial data.
func (m *metricNatsJetstreamConsumers) init() {
	m.data.SetName("nats.jetstream.consumers")
	m.data.SetDescription("Number of JetStream consumers.")
	m.data.SetUnit("{consumers}")
	m.data.SetEmptyGauge()
}

func (m *metricNatsJetstreamConsumers) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsJetstreamConsumers) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsJetstreamConsumers) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsJetstreamConsumers(cfg MetricConfig) metricNatsJetstreamConsumers {
	m := metricNatsJetstreamConsumers{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsJetstreamMemoryReserved struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.jetstream.memory.reserved metric with initial data.
func (m *metricNatsJetstreamMemoryReserved) init() {
	m.data.SetName("nats.jetstream.memory.reserved")
	m.data.SetDescription("Memory reserved by JetStream.")
	m.data.SetUnit("By")
	m.data.SetEmptyGauge()
}

func (m *metricNatsJetstreamMemoryReserved) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsJetstreamMemoryReserved) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsJetstreamMemoryReserved) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsJetstreamMemoryReserved(cfg MetricConfig) metricNatsJetstreamMemoryReserved {
	m := metricNatsJetstreamMemoryReserved{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsJetstreamMessages struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.jetstream.messages metric with initial data.
func (m *metricNatsJetstreamMessages) init() {
	m.data.SetName("nats.jetstream.messages")
	m.data.SetDescription("Total number of messages stored in JetStream.")
	m.data.SetUnit("{messages}")
	m.data.SetEmptyGauge()
}

func (m *metricNatsJetstreamMessages) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsJetstreamMessages) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsJetstreamMessages) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsJetstreamMessages(cfg MetricConfig) metricNatsJetstreamMessages {
	m := metricNatsJetstreamMessages{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsJetstreamStorageReserved struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.jetstream.storage.reserved metric with initial data.
func (m *metricNatsJetstreamStorageReserved) init() {
	m.data.SetName("nats.jetstream.storage.reserved")
	m.data.SetDescription("Disk storage reserved by JetStream.")
	m.data.SetUnit("By")
	m.data.SetEmptyGauge()
}

func (m *metricNatsJetstreamStorageReserved) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsJetstreamStorageReserved) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsJetstreamStorageReserved) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsJetstreamStorageReserved(cfg MetricConfig) metricNatsJetstreamStorageReserved {
	m := metricNatsJetstreamStorageReserved{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsJetstreamStreams struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.jetstream.streams metric with initial data.
func (m *metricNatsJetstreamStreams) init() {
	m.data.SetName("nats.jetstream.streams")
	m.data.SetDescription("Number of JetStream streams.")
	m.data.SetUnit("{streams}")
	m.data.SetEmptyGauge()
}

func (m *metricNatsJetstreamStreams) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsJetstreamStreams) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsJetstreamStreams) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsJetstreamStreams(cfg MetricConfig) metricNatsJetstreamStreams {
	m := metricNatsJetstreamStreams{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsServerBytesReceived struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.server.bytes.received metric with initial data.
func (m *metricNatsServerBytesReceived) init() {
	m.data.SetName("nats.server.bytes.received")
	m.data.SetDescription("Total number of bytes received by the NATS server since it started.")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNatsServerBytesReceived) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsServerBytesReceived) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsServerBytesReceived) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsServerBytesReceived(cfg MetricConfig) metricNatsServerBytesReceived {
	m := metricNatsServerBytesReceived{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsServerBytesSent struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.server.bytes.sent metric with initial data.
func (m *metricNatsServerBytesSent) init() {
	m.data.SetName("nats.server.bytes.sent")
	m.data.SetDescription("Total number of bytes sent by the NATS server since it started.")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNatsServerBytesSent) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsServerBytesSent) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsServerBytesSent) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsServerBytesSent(cfg MetricConfig) metricNatsServerBytesSent {
	m := metricNatsServerBytesSent{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsServerConnections struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.server.connections metric with initial data.
func (m *metricNatsServerConnections) init() {
	m.data.SetName("nats.server.connections")
	m.data.SetDescription("Number of active client connections to the NATS server.")
	m.data.SetUnit("{connections}")
	m.data.SetEmptyGauge()
}

func (m *metricNatsServerConnections) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsServerConnections) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsServerConnections) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsServerConnections(cfg MetricConfig) metricNatsServerConnections {
	m := metricNatsServerConnections{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsServerConnectionsTotal struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.server.connections.total metric with initial data.
func (m *metricNatsServerConnectionsTotal) init() {
	m.data.SetName("nats.server.connections.total")
	m.data.SetDescription("Total number of client connections to the NATS server since it started.")
	m.data.SetUnit("{connections}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNatsServerConnectionsTotal) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsServerConnectionsTotal) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsServerConnectionsTotal) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsServerConnectionsTotal(cfg MetricConfig) metricNatsServerConnectionsTotal {
	m := metricNatsServerConnectionsTotal{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsServerCPU struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.server.cpu metric with initial data.
func (m *metricNatsServerCPU) init() {
	m.data.SetName("nats.server.cpu")
	m.data.SetDescription("CPU usage of the NATS server process (0-100).")
	m.data.SetUnit("%")
	m.data.SetEmptyGauge()
}

func (m *metricNatsServerCPU) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsServerCPU) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsServerCPU) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsServerCPU(cfg MetricConfig) metricNatsServerCPU {
	m := metricNatsServerCPU{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsServerLeafNodes struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.server.leaf_nodes metric with initial data.
func (m *metricNatsServerLeafNodes) init() {
	m.data.SetName("nats.server.leaf_nodes")
	m.data.SetDescription("Number of active leaf node connections to the NATS server.")
	m.data.SetUnit("{leaf_nodes}")
	m.data.SetEmptyGauge()
}

func (m *metricNatsServerLeafNodes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsServerLeafNodes) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsServerLeafNodes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsServerLeafNodes(cfg MetricConfig) metricNatsServerLeafNodes {
	m := metricNatsServerLeafNodes{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsServerMaxConnections struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.server.max_connections metric with initial data.
func (m *metricNatsServerMaxConnections) init() {
	m.data.SetName("nats.server.max_connections")
	m.data.SetDescription("Maximum number of client connections allowed by the NATS server.")
	m.data.SetUnit("{connections}")
	m.data.SetEmptyGauge()
}

func (m *metricNatsServerMaxConnections) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsServerMaxConnections) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsServerMaxConnections) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsServerMaxConnections(cfg MetricConfig) metricNatsServerMaxConnections {
	m := metricNatsServerMaxConnections{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsServerMemory struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.server.memory metric with initial data.
func (m *metricNatsServerMemory) init() {
	m.data.SetName("nats.server.memory")
	m.data.SetDescription("Memory used by the NATS server process.")
	m.data.SetUnit("By")
	m.data.SetEmptyGauge()
}

func (m *metricNatsServerMemory) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsServerMemory) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsServerMemory) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsServerMemory(cfg MetricConfig) metricNatsServerMemory {
	m := metricNatsServerMemory{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsServerMessagesReceived struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.server.messages.received metric with initial data.
func (m *metricNatsServerMessagesReceived) init() {
	m.data.SetName("nats.server.messages.received")
	m.data.SetDescription("Total number of messages received by the NATS server since it started.")
	m.data.SetUnit("{messages}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNatsServerMessagesReceived) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsServerMessagesReceived) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsServerMessagesReceived) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsServerMessagesReceived(cfg MetricConfig) metricNatsServerMessagesReceived {
	m := metricNatsServerMessagesReceived{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsServerMessagesSent struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.server.messages.sent metric with initial data.
func (m *metricNatsServerMessagesSent) init() {
	m.data.SetName("nats.server.messages.sent")
	m.data.SetDescription("Total number of messages sent by the NATS server since it started.")
	m.data.SetUnit("{messages}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNatsServerMessagesSent) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsServerMessagesSent) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsServerMessagesSent) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsServerMessagesSent(cfg MetricConfig) metricNatsServerMessagesSent {
	m := metricNatsServerMessagesSent{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsServerRoutes struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.server.routes metric with initial data.
func (m *metricNatsServerRoutes) init() {
	m.data.SetName("nats.server.routes")
	m.data.SetDescription("Number of active cluster routes on the NATS server.")
	m.data.SetUnit("{routes}")
	m.data.SetEmptyGauge()
}

func (m *metricNatsServerRoutes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsServerRoutes) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsServerRoutes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsServerRoutes(cfg MetricConfig) metricNatsServerRoutes {
	m := metricNatsServerRoutes{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsServerSlowConsumers struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.server.slow_consumers metric with initial data.
func (m *metricNatsServerSlowConsumers) init() {
	m.data.SetName("nats.server.slow_consumers")
	m.data.SetDescription("Number of slow consumer events on the NATS server.")
	m.data.SetUnit("{consumers}")
	m.data.SetEmptyGauge()
}

func (m *metricNatsServerSlowConsumers) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsServerSlowConsumers) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsServerSlowConsumers) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsServerSlowConsumers(cfg MetricConfig) metricNatsServerSlowConsumers {
	m := metricNatsServerSlowConsumers{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNatsServerSubscriptions struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills nats.server.subscriptions metric with initial data.
func (m *metricNatsServerSubscriptions) init() {
	m.data.SetName("nats.server.subscriptions")
	m.data.SetDescription("Number of active subscriptions on the NATS server.")
	m.data.SetUnit("{subscriptions}")
	m.data.SetEmptyGauge()
}

func (m *metricNatsServerSubscriptions) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNatsServerSubscriptions) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNatsServerSubscriptions) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNatsServerSubscriptions(cfg MetricConfig) metricNatsServerSubscriptions {
	m := metricNatsServerSubscriptions{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                             MetricsBuilderConfig // config of the metrics builder.
	startTime                          pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                    int                  // maximum observed number of metrics per resource.
	metricsBuffer                      pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                          component.BuildInfo  // contains version information.
	metricNatsAccountBytesReceived     metricNatsAccountBytesReceived
	metricNatsAccountBytesSent         metricNatsAccountBytesSent
	metricNatsAccountConnections       metricNatsAccountConnections
	metricNatsAccountLeafNodes         metricNatsAccountLeafNodes
	metricNatsAccountMessagesReceived  metricNatsAccountMessagesReceived
	metricNatsAccountMessagesSent      metricNatsAccountMessagesSent
	metricNatsAccountSlowConsumers     metricNatsAccountSlowConsumers
	metricNatsAccountSubscriptions     metricNatsAccountSubscriptions
	metricNatsConnectionCount          metricNatsConnectionCount
	metricNatsJetstreamAPICalls        metricNatsJetstreamAPICalls
	metricNatsJetstreamAPIErrors       metricNatsJetstreamAPIErrors
	metricNatsJetstreamBytes           metricNatsJetstreamBytes
	metricNatsJetstreamConsumers       metricNatsJetstreamConsumers
	metricNatsJetstreamMemoryReserved  metricNatsJetstreamMemoryReserved
	metricNatsJetstreamMessages        metricNatsJetstreamMessages
	metricNatsJetstreamStorageReserved metricNatsJetstreamStorageReserved
	metricNatsJetstreamStreams         metricNatsJetstreamStreams
	metricNatsServerBytesReceived      metricNatsServerBytesReceived
	metricNatsServerBytesSent          metricNatsServerBytesSent
	metricNatsServerConnections        metricNatsServerConnections
	metricNatsServerConnectionsTotal   metricNatsServerConnectionsTotal
	metricNatsServerCPU                metricNatsServerCPU
	metricNatsServerLeafNodes          metricNatsServerLeafNodes
	metricNatsServerMaxConnections     metricNatsServerMaxConnections
	metricNatsServerMemory             metricNatsServerMemory
	metricNatsServerMessagesReceived   metricNatsServerMessagesReceived
	metricNatsServerMessagesSent       metricNatsServerMessagesSent
	metricNatsServerRoutes             metricNatsServerRoutes
	metricNatsServerSlowConsumers      metricNatsServerSlowConsumers
	metricNatsServerSubscriptions      metricNatsServerSubscriptions
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                             mbc,
		startTime:                          pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                      pmetric.NewMetrics(),
		buildInfo:                          settings.BuildInfo,
		metricNatsAccountBytesReceived:     newMetricNatsAccountBytesReceived(mbc.Metrics.NatsAccountBytesReceived),
		metricNatsAccountBytesSent:         newMetricNatsAccountBytesSent(mbc.Metrics.NatsAccountBytesSent),
		metricNatsAccountConnections:       newMetricNatsAccountConnections(mbc.Metrics.NatsAccountConnections),
		metricNatsAccountLeafNodes:         newMetricNatsAccountLeafNodes(mbc.Metrics.NatsAccountLeafNodes),
		metricNatsAccountMessagesReceived:  newMetricNatsAccountMessagesReceived(mbc.Metrics.NatsAccountMessagesReceived),
		metricNatsAccountMessagesSent:      newMetricNatsAccountMessagesSent(mbc.Metrics.NatsAccountMessagesSent),
		metricNatsAccountSlowConsumers:     newMetricNatsAccountSlowConsumers(mbc.Metrics.NatsAccountSlowConsumers),
		metricNatsAccountSubscriptions:     newMetricNatsAccountSubscriptions(mbc.Metrics.NatsAccountSubscriptions),
		metricNatsConnectionCount:          newMetricNatsConnectionCount(mbc.Metrics.NatsConnectionCount),
		metricNatsJetstreamAPICalls:        newMetricNatsJetstreamAPICalls(mbc.Metrics.NatsJetstreamAPICalls),
		metricNatsJetstreamAPIErrors:       newMetricNatsJetstreamAPIErrors(mbc.Metrics.NatsJetstreamAPIErrors),
		metricNatsJetstreamBytes:           newMetricNatsJetstreamBytes(mbc.Metrics.NatsJetstreamBytes),
		metricNatsJetstreamConsumers:       newMetricNatsJetstreamConsumers(mbc.Metrics.NatsJetstreamConsumers),
		metricNatsJetstreamMemoryReserved:  newMetricNatsJetstreamMemoryReserved(mbc.Metrics.NatsJetstreamMemoryReserved),
		metricNatsJetstreamMessages:        newMetricNatsJetstreamMessages(mbc.Metrics.NatsJetstreamMessages),
		metricNatsJetstreamStorageReserved: newMetricNatsJetstreamStorageReserved(mbc.Metrics.NatsJetstreamStorageReserved),
		metricNatsJetstreamStreams:         newMetricNatsJetstreamStreams(mbc.Metrics.NatsJetstreamStreams),
		metricNatsServerBytesReceived:      newMetricNatsServerBytesReceived(mbc.Metrics.NatsServerBytesReceived),
		metricNatsServerBytesSent:          newMetricNatsServerBytesSent(mbc.Metrics.NatsServerBytesSent),
		metricNatsServerConnections:        newMetricNatsServerConnections(mbc.Metrics.NatsServerConnections),
		metricNatsServerConnectionsTotal:   newMetricNatsServerConnectionsTotal(mbc.Metrics.NatsServerConnectionsTotal),
		metricNatsServerCPU:                newMetricNatsServerCPU(mbc.Metrics.NatsServerCPU),
		metricNatsServerLeafNodes:          newMetricNatsServerLeafNodes(mbc.Metrics.NatsServerLeafNodes),
		metricNatsServerMaxConnections:     newMetricNatsServerMaxConnections(mbc.Metrics.NatsServerMaxConnections),
		metricNatsServerMemory:             newMetricNatsServerMemory(mbc.Metrics.NatsServerMemory),
		metricNatsServerMessagesReceived:   newMetricNatsServerMessagesReceived(mbc.Metrics.NatsServerMessagesReceived),
		metricNatsServerMessagesSent:       newMetricNatsServerMessagesSent(mbc.Metrics.NatsServerMessagesSent),
		metricNatsServerRoutes:             newMetricNatsServerRoutes(mbc.Metrics.NatsServerRoutes),
		metricNatsServerSlowConsumers:      newMetricNatsServerSlowConsumers(mbc.Metrics.NatsServerSlowConsumers),
		metricNatsServerSubscriptions:      newMetricNatsServerSubscriptions(mbc.Metrics.NatsServerSubscriptions),
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricNatsAccountBytesReceived.emit(ils.Metrics())
	mb.metricNatsAccountBytesSent.emit(ils.Metrics())
	mb.metricNatsAccountConnections.emit(ils.Metrics())
	mb.metricNatsAccountLeafNodes.emit(ils.Metrics())
	mb.metricNatsAccountMessagesReceived.emit(ils.Metrics())
	mb.metricNatsAccountMessagesSent.emit(ils.Metrics())
	mb.metricNatsAccountSlowConsumers.emit(ils.Metrics())
	mb.metricNatsAccountSubscriptions.emit(ils.Metrics())
	mb.metricNatsConnectionCount.emit(ils.Metrics())
	mb.metricNatsJetstreamAPICalls.emit(ils.Metrics())
	mb.metricNatsJetstreamAPIErrors.emit(ils.Metrics())
	mb.metricNatsJetstreamBytes.emit(ils.Metrics())
	mb.metricNatsJetstreamConsumers.emit(ils.Metrics())
	mb.metricNatsJetstreamMemoryReserved.emit(ils.Metrics())
	mb.metricNatsJetstreamMessages.emit(ils.Metrics())
	mb.metricNatsJetstreamStorageReserved.emit(ils.Metrics())
	mb.metricNatsJetstreamStreams.emit(ils.Metrics())
	mb.metricNatsServerBytesReceived.emit(ils.Metrics())
	mb.metricNatsServerBytesSent.emit(ils.Metrics())
	mb.metricNatsServerConnections.emit(ils.Metrics())
	mb.metricNatsServerConnectionsTotal.emit(ils.Metrics())
	mb.metricNatsServerCPU.emit(ils.Metrics())
	mb.metricNatsServerLeafNodes.emit(ils.Metrics())
	mb.metricNatsServerMaxConnections.emit(ils.Metrics())
	mb.metricNatsServerMemory.emit(ils.Metrics())
	mb.metricNatsServerMessagesReceived.emit(ils.Metrics())
	mb.metricNatsServerMessagesSent.emit(ils.Metrics())
	mb.metricNatsServerRoutes.emit(ils.Metrics())
	mb.metricNatsServerSlowConsumers.emit(ils.Metrics())
	mb.metricNatsServerSubscriptions.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordNatsAccountBytesReceivedDataPoint adds a data point to nats.account.bytes.received metric.
func (mb *MetricsBuilder) RecordNatsAccountBytesReceivedDataPoint(ts pcommon.Timestamp, val int64, accountAttributeValue string) {
	mb.metricNatsAccountBytesReceived.recordDataPoint(mb.startTime, ts, val, accountAttributeValue)
}

// RecordNatsAccountBytesSentDataPoint adds a data point to nats.account.bytes.sent metric.
func (mb *MetricsBuilder) RecordNatsAccountBytesSentDataPoint(ts pcommon.Timestamp, val int64, accountAttributeValue string) {
	mb.metricNatsAccountBytesSent.recordDataPoint(mb.startTime, ts, val, accountAttributeValue)
}

// RecordNatsAccountConnectionsDataPoint adds a data point to nats.account.connections metric.
func (mb *MetricsBuilder) RecordNatsAccountConnectionsDataPoint(ts pcommon.Timestamp, val int64, accountAttributeValue string) {
	mb.metricNatsAccountConnections.recordDataPoint(mb.startTime, ts, val, accountAttributeValue)
}

// RecordNatsAccountLeafNodesDataPoint adds a data point to nats.account.leaf_nodes metric.
func (mb *MetricsBuilder) RecordNatsAccountLeafNodesDataPoint(ts pcommon.Timestamp, val int64, accountAttributeValue string) {
	mb.metricNatsAccountLeafNodes.recordDataPoint(mb.startTime, ts, val, accountAttributeValue)
}

// RecordNatsAccountMessagesReceivedDataPoint adds a data point to nats.account.messages.received metric.
func (mb *MetricsBuilder) RecordNatsAccountMessagesReceivedDataPoint(ts pcommon.Timestamp, val int64, accountAttributeValue string) {
	mb.metricNatsAccountMessagesReceived.recordDataPoint(mb.startTime, ts, val, accountAttributeValue)
}

// RecordNatsAccountMessagesSentDataPoint adds a data point to nats.account.messages.sent metric.
func (mb *MetricsBuilder) RecordNatsAccountMessagesSentDataPoint(ts pcommon.Timestamp, val int64, accountAttributeValue string) {
	mb.metricNatsAccountMessagesSent.recordDataPoint(mb.startTime, ts, val, accountAttributeValue)
}

// RecordNatsAccountSlowConsumersDataPoint adds a data point to nats.account.slow_consumers metric.
func (mb *MetricsBuilder) RecordNatsAccountSlowConsumersDataPoint(ts pcommon.Timestamp, val int64, accountAttributeValue string) {
	mb.metricNatsAccountSlowConsumers.recordDataPoint(mb.startTime, ts, val, accountAttributeValue)
}

// RecordNatsAccountSubscriptionsDataPoint adds a data point to nats.account.subscriptions metric.
func (mb *MetricsBuilder) RecordNatsAccountSubscriptionsDataPoint(ts pcommon.Timestamp, val int64, accountAttributeValue string) {
	mb.metricNatsAccountSubscriptions.recordDataPoint(mb.startTime, ts, val, accountAttributeValue)
}

// RecordNatsConnectionCountDataPoint adds a data point to nats.connection.count metric.
func (mb *MetricsBuilder) RecordNatsConnectionCountDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNatsConnectionCount.recordDataPoint(mb.startTime, ts, val)
}

// RecordNatsJetstreamAPICallsDataPoint adds a data point to nats.jetstream.api.calls metric.
func (mb *MetricsBuilder) RecordNatsJetstreamAPICallsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNatsJetstreamAPICalls.recordDataPoint(mb.startTime, ts, val)
}

// RecordNatsJetstreamAPIErrorsDataPoint adds a data point to nats.jetstream.api.errors metric.
func (mb *MetricsBuilder) RecordNatsJetstreamAPIErrorsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNatsJetstreamAPIErrors.recordDataPoint(mb.startTime, ts, val)
}

// RecordNatsJetstreamBytesDataPoint adds a data point to nats.jetstream.bytes metric.
func (mb *MetricsBuilder) RecordNatsJetstreamBytesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNatsJetstreamBytes.recordDataPoint(mb.startTime, ts, val)
}

// RecordNatsJetstreamConsumersDataPoint adds a data point to nats.jetstream.consumers metric.
func (mb *MetricsBuilder) RecordNatsJetstreamConsumersDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNatsJetstreamConsumers.recordDataPoint(mb.startTime, ts, val)
}

// RecordNatsJetstreamMemoryReservedDataPoint adds a data point to nats.jetstream.memory.reserved metric.
func (mb *MetricsBuilder) RecordNatsJetstreamMemoryReservedDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNatsJetstreamMemoryReserved.recordDataPoint(mb.startTime, ts, val)
}

// RecordNatsJetstreamMessagesDataPoint adds a data point to nats.jetstream.messages metric.
func (mb *MetricsBuilder) RecordNatsJetstreamMessagesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNatsJetstreamMessages.recordDataPoint(mb.startTime, ts, val)
}

// RecordNatsJetstreamStorageReservedDataPoint adds a data point to nats.jetstream.storage.reserved metric.
func (mb *MetricsBuilder) RecordNatsJetstreamStorageReservedDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNatsJetstreamStorageReserved.recordDataPoint(mb.startTime, ts, val)
}

// RecordNatsJetstreamStreamsDataPoint adds a data point to nats.jetstream.streams metric.
func (mb *MetricsBuilder) RecordNatsJetstreamStreamsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNatsJetstreamStreams.recordDataPoint(mb.startTime, ts, val)
}

// RecordNatsServerBytesReceivedDataPoint adds a data point to nats.server.bytes.received metric.
func (mb *MetricsBuilder) RecordNatsServerBytesReceivedDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNatsServerBytesReceived.recordDataPoint(mb.startTime, ts, val)
}

// RecordNatsServerBytesSentDataPoint adds a data point to nats.server.bytes.sent metric.
func (mb *MetricsBuilder) RecordNatsServerBytesSentDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNatsServerBytesSent.recordDataPoint(mb.startTime, ts, val)
}

// RecordNatsServerConnectionsDataPoint adds a data point to nats.server.connections metric.
func (mb *MetricsBuilder) RecordNatsServerConnectionsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNatsServerConnections.recordDataPoint(mb.startTime, ts, val)
}

// RecordNatsServerConnectionsTotalDataPoint adds a data point to nats.server.connections.total metric.
func (mb *MetricsBuilder) RecordNatsServerConnectionsTotalDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNatsServerConnectionsTotal.recordDataPoint(mb.startTime, ts, val)
}

// RecordNatsServerCPUDataPoint adds a data point to nats.server.cpu metric.
func (mb *MetricsBuilder) RecordNatsServerCPUDataPoint(ts pcommon.Timestamp, val float64) {
	mb.metricNatsServerCPU.recordDataPoint(mb.startTime, ts, val)
}

// RecordNatsServerLeafNodesDataPoint adds a data point to nats.server.leaf_nodes metric.
func (mb *MetricsBuilder) RecordNatsServerLeafNodesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNatsServerLeafNodes.recordDataPoint(mb.startTime, ts, val)
}

// RecordNatsServerMaxConnectionsDataPoint adds a data point to nats.server.max_connections metric.
func (mb *MetricsBuilder) RecordNatsServerMaxConnectionsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNatsServerMaxConnections.recordDataPoint(mb.startTime, ts, val)
}

// RecordNatsServerMemoryDataPoint adds a data point to nats.server.memory metric.
func (mb *MetricsBuilder) RecordNatsServerMemoryDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNatsServerMemory.recordDataPoint(mb.startTime, ts, val)
}

// RecordNatsServerMessagesReceivedDataPoint adds a data point to nats.server.messages.received metric.
func (mb *MetricsBuilder) RecordNatsServerMessagesReceivedDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNatsServerMessagesReceived.recordDataPoint(mb.startTime, ts, val)
}

// RecordNatsServerMessagesSentDataPoint adds a data point to nats.server.messages.sent metric.
func (mb *MetricsBuilder) RecordNatsServerMessagesSentDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNatsServerMessagesSent.recordDataPoint(mb.startTime, ts, val)
}

// RecordNatsServerRoutesDataPoint adds a data point to nats.server.routes metric.
func (mb *MetricsBuilder) RecordNatsServerRoutesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNatsServerRoutes.recordDataPoint(mb.startTime, ts, val)
}

// RecordNatsServerSlowConsumersDataPoint adds a data point to nats.server.slow_consumers metric.
func (mb *MetricsBuilder) RecordNatsServerSlowConsumersDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNatsServerSlowConsumers.recordDataPoint(mb.startTime, ts, val)
}

// RecordNatsServerSubscriptionsDataPoint adds a data point to nats.server.subscriptions metric.
func (mb *MetricsBuilder) RecordNatsServerSubscriptionsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNatsServerSubscriptions.recordDataPoint(mb.startTime, ts, val)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
